- job:
    name: neutron-dynamic-routing-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/neutron-dynamic-routing-dsvm-functional/run.yaml
    post-run: playbooks/neutron-dynamic-routing-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing

- job:
    name: neutron-dynamic-routing-dsvm-tempest-api
    parent: legacy-dsvm-base
    run: playbooks/neutron-dynamic-routing-dsvm-tempest-api/run.yaml
    post-run: playbooks/neutron-dynamic-routing-dsvm-tempest-api/post.yaml
    timeout: 7500
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing
      - openstack/tempest

- job:
    name: neutron-dynamic-routing-dsvm-tempest-scenario-basic
    parent: legacy-dsvm-base
    run: playbooks/neutron-dynamic-routing-dsvm-tempest-scenario-basic/run.yaml
    post-run: playbooks/neutron-dynamic-routing-dsvm-tempest-scenario-basic/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing
      - openstack/tempest

- job:
    name: neutron-dynamic-routing-dsvm-tempest-scenario-ipv4
    parent: legacy-dsvm-base
    run: playbooks/neutron-dynamic-routing-dsvm-tempest-scenario-ipv4/run.yaml
    post-run: playbooks/neutron-dynamic-routing-dsvm-tempest-scenario-ipv4/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing
      - openstack/tempest

- job:
    name: neutron-dynamic-routing-dsvm-tempest-scenario-ipv6
    parent: legacy-dsvm-base
    run: playbooks/neutron-dynamic-routing-dsvm-tempest-scenario-ipv6/run.yaml
    post-run: playbooks/neutron-dynamic-routing-dsvm-tempest-scenario-ipv6/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing
      - openstack/tempest

- job:
    name: neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4
    parent: legacy-dsvm-base
    run: playbooks/neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4/run.yaml
    post-run: playbooks/neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing
      - openstack/tempest

- job:
    name: periodic-neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4
    parent: legacy-dsvm-base
    run: playbooks/periodic-neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4/run.yaml
    post-run: playbooks/periodic-neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4/post.yaml
    timeout: 7800
    branches: master
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-dynamic-routing
      - openstack/tempest

- project:
    check:
      jobs:
        - neutron-dynamic-routing-dsvm-functional
        - neutron-dynamic-routing-dsvm-tempest-api
        - neutron-dynamic-routing-dsvm-tempest-scenario-basic:
            voting: false
        - neutron-dynamic-routing-dsvm-tempest-scenario-ipv4:
            voting: false
        - neutron-dynamic-routing-dsvm-tempest-scenario-ipv6:
            voting: false
    gate:
      jobs:
        - neutron-dynamic-routing-dsvm-functional
        - neutron-dynamic-routing-dsvm-tempest-api
    experimental:
      jobs:
        - neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4
    periodic:
      jobs:
        - periodic-neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4
#        - legacy-periodic-neutron-dynamic-routing-dsvm-tempest-with-ryu-master-scenario-ipv4
