- job:
    name: neutron-dynamic-routing-static-wallaby
    parent: neutron-tempest-plugin-dynamic-routing-wallaby
    vars:
      devstack_localrc:
        BGP_SCHEDULER_DRIVER: neutron_dynamic_routing.services.bgp.scheduler.bgp_dragent_scheduler.StaticScheduler
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
             neutron_plugin_options:
               bgp_schedule_speakers_to_agents: true

- job:
    name: neutron-dynamic-routing-functional
    parent: neutron-functional
    vars:
      project_name: neutron-dynamic-routing-functional
      # NOTE(amotoki): neutron-functional sets tox_install_siblings to false.
      # This needs to be true so that neutron from its repo is installed into
      # tox env.
      # We need to check tox_install_siblings false is required
      # in neutron-functional job.
      tox_install_siblings: true

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-neutron
      - openstack-python3-wallaby-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-dynamic-routing-functional
        - neutron-dynamic-routing-static-wallaby
        - neutron-tempest-plugin-dynamic-routing-wallaby
    gate:
      jobs:
        - neutron-dynamic-routing-functional
        - neutron-tempest-plugin-dynamic-routing-wallaby
