- job:
    name: neutron-dynamic-routing-static
    parent: neutron-tempest-plugin-dynamic-routing
    vars:
      devstack_localrc:
        BGP_SCHEDULER_DRIVER: neutron_dynamic_routing.services.bgp.scheduler.bgp_dragent_scheduler.StaticScheduler
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
             neutron_plugin_options:
               bgp_schedule_speakers_to_agents: true

- job:
    name: neutron-dynamic-routing-functional
    parent: neutron-functional
    vars:
      project_name: neutron-dynamic-routing-functional
      tox_envlist: functional
      # NOTE(amotoki): neutron-functional sets tox_install_siblings to false.
      # This needs to be true so that neutron from its repo is installed into
      # tox env.
      # We need to check tox_install_siblings false is required
      # in neutron-functional job.
      tox_install_siblings: true

- job:
    name: neutron-dynamic-routing-openstack-tox-py310-with-sqlalchemy-main
    parent: openstack-tox-py310-with-oslo-master
    required-projects:
      - name: github.com/sqlalchemy/sqlalchemy
        override-checkout: main
      - name: github.com/sqlalchemy/alembic
        override-checkout: main
      - openstack/oslo.db
      - openstack/neutron-lib
      - openstack/neutron

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-neutron
      - openstack-python3-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-dynamic-routing-functional
        - neutron-dynamic-routing-static
        - neutron-tempest-plugin-dynamic-routing
    gate:
      jobs:
        - neutron-dynamic-routing-functional
        - neutron-tempest-plugin-dynamic-routing
    experimental:
      jobs:
        - openstack-tox-py310-with-oslo-master
        - neutron-dynamic-routing-openstack-tox-py310-with-sqlalchemy-main
    periodic-weekly:
      jobs:
        - openstack-tox-py311
        - openstack-tox-py310-with-oslo-master
        - neutron-dynamic-routing-openstack-tox-py310-with-sqlalchemy-main
        - neutron-tempest-plugin-dynamic-routing
        - neutron-dynamic-routing-functional
